{% set name = "zeroc-ice" %}
{% set version = "3.6.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}{{ environ.get('VERSION_SUFFIX', '') }}"

build:
  number: 0
  noarch: generic
  script_env:
    - VERSION_SUFFIX

requirements:
  run:
    - zeroc-ice-bin={{ version }}
    - zeroc-ice-python={{ version }}

test:
  imports:
    - Ice
  commands:
    - icegridnode --version

about:
  home: https://zeroc.com
  license: GNU General Public v2 (GPLv2)
  license_family: GPL2
  summary: Meta package for the Zeroc Ice binaries and Python module.
  description: |
    Ice is a comprehensive RPC framework with support for Python, C++, .NET, Java, JavaScript and more.
    This meta-package includes the Zeroc Ice binaries and Python module.

extra:
  recipe-maintainers:
    - ome
