{% set name = "zeroc-ice" %}
{% set version = "3.6.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe0ebacb6996870d0aa46511c126f9b3cfe88257517a5608d63332e9b6fb1717
  patches:
    # https://forums.zeroc.com/discussion/46580/python-3-6-3-ice-3-5-1-crash-on-exit
    # https://github.com/zeroc-ice/ice/commit/5008cf82774e77b119d371a2677ac36060184e78
    - 0001-ice8496-python_crash_on_exit.diff

build:
  number: 0
  entry_points:
    - slice2py=slice2py:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - {{ compiler('cxx') }}
  skip: True  # [win and vc<14]
  host:
    - bzip2
    - expat
    - openssl
    - pip
    - python
  run:
    - python
    - openssl
    - vc 9    # [win and py27]

test:
  imports:
    - Glacier2
    - Ice
    - IceBox
    - IceGrid
    - IceMX
    - IcePatch2
    - IceStorm
  commands:
    - slice2py --help

about:
  home: https://zeroc.com
  license: GNU General Public v2 (GPLv2)
  license_family: GPL2
  summary: Ice is a comprehensive RPC framework with support for Python, C++, .NET, Java, JavaScript and more.

extra:
  recipe-maintainers:
    - ome
